server:
  port: 8080

spring:
  profiles:
    include: security
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

file:
  files: /home/ec2-user/community/files

# Swagger Settings
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**

# Spring Security Settings
jwt:
  secretKey: sdadpaosidopwkwqodjasdjaskjfdslhjsghldsgfsdfsdgdslgjoeqjrqwjedlkwqdjlsajdkl
