server:
  port: 9998

spring:
  profiles:
    include: security
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB

community:
  file:
    image: /community/images

# Swagger Settings
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**

# Spring Security Settings
jwt:
  secretKey: sdadpaosidopwkwqodjasdjaskjfdslhjsghldsgfsdfsdgdslgjoeqjrqwjedlkwqdjlsajdkl
permission:
  permit-all-urls:
    - /api/members/login
    - /api/members/**
    - /images/**
    - /swagger
    - /swagger/**
    - /swagger-ui/**
    - /v3/api-docs/**
